[project]
name = "obs-agent"
version = "0.1.0"
description = "A simple observability agent to actively learn about containers and observability"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "httpx>=0.28.1",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "uvicorn>=0.48.0",
]
